export const GET_COUNTRIES = 'GET_COUNTRIES';

export const FILTER_COUNTRIES = 'FILTER_COUNTRIES';

export const ORDER_COUNTRIES = 'ORDER_COUNTRIES';

export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';

export const ADD_TOURIST_ACTIVITIES = 'ADD_TOURIST_ACTIVITIES'; 

export const GET_TOURIST_ACTIVITIES = 'GET_TOURIST_ACTIVITIES'; 

